# Generated by Django 6.0.6 on 2026-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
