# Generated by Django 6.0.6 on 2026-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONCERT', 'Konsert'), ('CONFERENCE', 'Konfrans'), ('SPORT', 'İdman'), ('THEATER', 'Teatr'), ('FESTIVAL', 'Festival')], default='CONCERT', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Baku', max_length=100),
        ),
    ]
