# Generated by Django 6.0.6 on 2026-07-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_category_event_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='sales_end',
            new_name='end_sale_date',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='quantity',
            new_name='quantity_total',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='sales_start',
            new_name='start_sale_date',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='category',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='currency',
            field=models.CharField(choices=[('AZN', 'Azerbaijani Manat'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira')], default='AZN', max_length=3),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_per_order',
            field=models.PositiveIntegerField(default=10, help_text='Максимум билетов в одном заказе'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='min_per_order',
            field=models.PositiveIntegerField(default=1, help_text='Минимум билетов в одном заказе (например, 3 для Group)'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, help_text='Сколько уже продано'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='seating_type',
            field=models.CharField(choices=[('GA', 'General Admission'), ('RESERVED', 'Reserved Seating')], default='GA', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype'),
        ),
    ]
