# Generated by Django 6.0.6 on 2026-07-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_order_event_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сколько денег сэкономил клиент', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма к оплате после скидки', max_digits=10),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Сам промокод, например SUMMER20', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Процент (%)'), ('FIXED', 'Фиксированная сумма')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Размер скидки (например, 20 для 20%)', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Максимальное количество использований (оставь пустым для безлимита)', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Сколько раз уже применили')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='events.promocode'),
        ),
    ]
