# Generated by Django 6.0.6 on 2026-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_order_discount_amount_order_final_price_promocode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Код валюты (например, USD, EUR, TRY)', max_length=3, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Сколько AZN стоит 1 единица этой валюты (Например, для USD введите 1.70)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда курс обновлялся в последний раз')),
            ],
        ),
    ]
