# Generated by Django 6.0.6 on 2026-07-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена перепродажи')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активно'), ('SOLD', 'Продано'), ('CANCELLED', 'Отменено')], default='ACTIVE', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выставления')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resale_listing', to='events.orderitem', verbose_name='Билет')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_listings', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
    ]
