# Generated by Django 6.0.6 on 2026-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_resalelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_insurance',
            field=models.BooleanField(default=False, verbose_name='Страховка отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость страховки'),
        ),
    ]
