# Generated by Django 6.0.6 on 2026-08-05 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_giftcard_order_gift_card_discount_order_gift_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя спикера')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания / Должность')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkedIn')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сессии')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('location_hall', models.CharField(blank=True, help_text='Название зала (например, Зал А, Main Stage)', max_length=255, null=True)),
                ('track_name', models.CharField(blank=True, help_text='Название потока (например, Tech Track, Marketing Track)', max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_sessions', to='events.event')),
                ('speakers', models.ManyToManyField(blank=True, related_name='sessions', to='events.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.agendasession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
    ]
