# Generated by Django 6.0.6 on 2026-08-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_speaker_agendasession_attendeeschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема выступления')),
                ('summary', models.TextField(verbose_name='Краткое описание (Abstract)')),
                ('status', models.CharField(choices=[('PENDING', 'Gözlənilir (Pending)'), ('ACCEPTED', 'Qəbul edilib (Accepted)'), ('REJECTED', 'Rədd edilib (Rejected)')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_submissions', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('level', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], default='SILVER', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на логотип')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт спонсора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.event')),
            ],
        ),
    ]
